<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="1" ignored="0" total="10" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="iBridge" duration-ms="489228" started-at="2022-05-10T08:04:05Z" finished-at="2022-05-10T08:12:14Z">
    <groups>
    </groups>
    <test name="iBridge3" duration-ms="489228" started-at="2022-05-10T08:04:05Z" finished-at="2022-05-10T08:12:14Z">
      <class name="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="setup" is-config="true" duration-ms="4859" started-at="2022-05-10T08:04:05Z" finished-at="2022-05-10T08:04:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initiateCaseIndividuallyExtended()[pri:1, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="initiateCaseIndividuallyExtended" duration-ms="79407" started-at="2022-05-10T08:04:10Z" finished-at="2022-05-10T08:05:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateCaseIndividuallyExtended -->
        <test-method status="PASS" signature="pendingCaseSubmissionVerification()[pri:2, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="pendingCaseSubmissionVerification" duration-ms="4446" started-at="2022-05-10T08:05:29Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.initiateCaseIndividuallyExtended" finished-at="2022-05-10T08:05:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pendingCaseSubmissionVerification -->
        <test-method status="PASS" signature="candidateEmailVerification()[pri:3, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="candidateEmailVerification" duration-ms="3346" started-at="2022-05-10T08:05:34Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.pendingCaseSubmissionVerification" finished-at="2022-05-10T08:05:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateEmailVerification -->
        <test-method status="PASS" signature="candidateLoginAccount()[pri:4, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="candidateLoginAccount" duration-ms="213830" started-at="2022-05-10T08:05:37Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.candidateEmailVerification" finished-at="2022-05-10T08:09:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateLoginAccount -->
        <test-method status="FAIL" signature="submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="submittedForVerification" duration-ms="182902" started-at="2022-05-10T08:09:11Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.candidateLoginAccount" finished-at="2022-05-10T08:12:14Z">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h3[contains(text(),'Case Submission Summary')]' (tried for 120 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //h3[contains(text(),'Case Submission Summary')]' (tried for 120 second(s) with 500 milliseconds interval)
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:113)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:283)
at com.iBridge.pageobject.LoginPage.verifyDashboardCaseSubmissionSummaryText(LoginPage.java:56)
at com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedForVerification(TC_InitiateCaseIndividuallyExtended_01.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//h3[contains(text(),'Case Submission Summary')]"}
  (Session info: chrome=101.0.4951.41)
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ARS-NBT-LAP-250', ip: '192.168.0.100', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-40-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.41, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.zYAyEo}, goog:chromeOptions: {debuggerAddress: localhost:37213}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 0b7c93fbca257901db419496338d3274
*** Element info: {Using=xpath, value=//h3[contains(text(),'Case Submission Summary')]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:424)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy9.isDisplayed(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:44)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:301)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:298)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedForVerification -->
        <test-method status="SKIP" signature="submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="submittedCasesTrackerWipCases" duration-ms="0" started-at="2022-05-10T08:12:14Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedForVerification" finished-at="2022-05-10T08:12:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedCasesTrackerWipCases -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="verifyInsufficientDocsQcAllocator" duration-ms="0" started-at="2022-05-10T08:12:14Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases" finished-at="2022-05-10T08:12:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQcAllocator -->
        <test-method status="SKIP" signature="searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="searchClientArsNoCaseList" duration-ms="0" started-at="2022-05-10T08:12:14Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases" finished-at="2022-05-10T08:12:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchClientArsNoCaseList -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="verifyInsufficientDocsQuality" duration-ms="0" started-at="2022-05-10T08:12:14Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator" finished-at="2022-05-10T08:12:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQuality -->
        <test-method status="SKIP" signature="verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="verifyInsufficientAllocator" duration-ms="0" started-at="2022-05-10T08:12:14Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality" finished-at="2022-05-10T08:12:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientAllocator -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@79b4d0f]" name="tearDown" is-config="true" duration-ms="143" started-at="2022-05-10T08:12:14Z" finished-at="2022-05-10T08:12:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01 -->
    </test> <!-- iBridge3 -->
  </suite> <!-- iBridge -->
</testng-results>
