<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="1" ignored="0" total="10" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="iBridge" duration-ms="325942" started-at="2022-07-04T12:54:16Z" finished-at="2022-07-04T12:59:42Z">
    <groups>
    </groups>
    <test name="iBridge3" duration-ms="325942" started-at="2022-07-04T12:54:16Z" finished-at="2022-07-04T12:59:42Z">
      <class name="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="setup" is-config="true" duration-ms="6147" started-at="2022-07-04T12:54:16Z" finished-at="2022-07-04T12:54:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initiateCaseIndividuallyExtended()[pri:1, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="initiateCaseIndividuallyExtended" duration-ms="55556" started-at="2022-07-04T12:54:22Z" finished-at="2022-07-04T12:55:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateCaseIndividuallyExtended -->
        <test-method status="PASS" signature="pendingCaseSubmissionVerification()[pri:2, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="pendingCaseSubmissionVerification" duration-ms="10080" started-at="2022-07-04T12:55:18Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.initiateCaseIndividuallyExtended" finished-at="2022-07-04T12:55:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pendingCaseSubmissionVerification -->
        <test-method status="PASS" signature="candidateEmailVerification()[pri:3, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="candidateEmailVerification" duration-ms="9262" started-at="2022-07-04T12:55:28Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.pendingCaseSubmissionVerification" finished-at="2022-07-04T12:55:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateEmailVerification -->
        <test-method status="FAIL" signature="candidateLoginAccount()[pri:4, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="candidateLoginAccount" duration-ms="244574" started-at="2022-07-04T12:55:37Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.candidateEmailVerification" finished-at="2022-07-04T12:59:42Z">
          <exception class="org.openqa.selenium.ElementNotInteractableException">
            <message>
              <![CDATA[element not interactable
  (Session info: headless chrome=101.0.4951.54)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ARS-NBT-LAP-068', ip: '192.168.121.30', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-51-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.flSrBZ}, goog:chromeOptions: {debuggerAddress: localhost:39159}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 65b1e0c1df6c8ff96ba677fc15fb1b9d]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: headless chrome=101.0.4951.54)
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ARS-NBT-LAP-068', ip: '192.168.121.30', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-51-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.flSrBZ}, goog:chromeOptions: {debuggerAddress: localhost:39159}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 65b1e0c1df6c8ff96ba677fc15fb1b9d
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:100)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy8.sendKeys(Unknown Source)
at com.iBridge.pageobject.InitiateCaseIndividuallyExtended.professionalReference(InitiateCaseIndividuallyExtended.java:349)
at com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.candidateLoginAccount(TC_InitiateCaseIndividuallyExtended_01.java:208)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementNotInteractableException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateLoginAccount -->
        <test-method status="SKIP" signature="submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="submittedForVerification" duration-ms="1" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.candidateLoginAccount" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedForVerification -->
        <test-method status="SKIP" signature="submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="submittedCasesTrackerWipCases" duration-ms="0" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedForVerification" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedCasesTrackerWipCases -->
        <test-method status="SKIP" signature="searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="searchClientArsNoCaseList" duration-ms="0" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchClientArsNoCaseList -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="verifyInsufficientDocsQcAllocator" duration-ms="0" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.submittedCasesTrackerWipCases" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQcAllocator -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="verifyInsufficientDocsQuality" duration-ms="0" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQcAllocator" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQuality -->
        <test-method status="SKIP" signature="verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447]" name="verifyInsufficientAllocator" duration-ms="0" started-at="2022-07-04T12:59:42Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientDocsQuality" finished-at="2022-07-04T12:59:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCaseIndividuallyExtended_01.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientAllocator -->
      </class> <!-- com.iBridge.testcases.TC_InitiateCaseIndividuallyExtended_01 -->
    </test> <!-- iBridge3 -->
  </suite> <!-- iBridge -->
</testng-results>
